import {
    BEDROCK_LISTING_GENERATION,
    BEDROCK_VIDEO_ANALYSIS,
    PERPLEXITY_PRODUCT_RESEARCH,
} from "../../../ai-prompts.private";

const AI_OPERATIONS = {
    BEDROCK_VIDEO_ANALYSIS,
    BEDROCK_LISTING_GENERATION,
    PERPLEXITY_PRODUCT_RESEARCH,
};

export default AI_OPERATIONS;
